#!/bin/bash
if [ -f .env ]; then
  export $(echo $(cat .env | sed 's/#.*//g'| xargs) | envsubst)

  home=$(pwd)
  file="list.txt"
  count=0
  timestamp=`date +"%Y-%m-%d %T"`

  if [[ $1 = 'expanded' ]] ; then
    # TBD
    walk() {
      local indent="${2:-0}"
      printf "%*s%s\n" $indent '' "$1"
      for entry in "$1"/*; do
        [[ -d "$entry" ]] && walk "$entry" $((indent+2))
      done
    }

    walk $BASE_PATH;
  else
    cd $BASE_PATH

    for f in */; do
      text+="${f%/}\n"
      let count++
    done

    cd $home

    echo -n "" > $file
    printf "$count|$timestamp\n" >> $file
    printf "$text" >> $file
    echo "*** Updated $file ($count artists)"
  fi

  if [[ $1 = 'deploy' ]] ; then
    git add . && \
    git add -u && \
    git commit -m "Update database ($count artists)" && \
    git push origin HEAD
    echo "*** Deployed new version to Github ($count artists)."
  fi

else
  echo "You need to set the BASE_PATH in .env to build the list."
fi
